---
- name: Creates ec2 instances
  hosts: localhost 
  tasks:
    - name: Create R1soft Server
      ec2: 
        key_name: "ansible"
        assign_public_ip: yes
        instance_type: "t2.micro"
        region: "eu-west-1"
        image: "ami-00035f41c82244dab"
        vpc_subnet_id: "subnet-1244255a"
